import React, { createContext, useContext, useState } from 'react';

type Language = 'es' | 'en' | 'pt';

const translations = {
  es: {
    // General
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    email: 'Email',
    password: 'Password',
    name: 'Nombre',
    create_account: 'Crear Cuenta',
    entering: 'Entrando...',
    registering: 'Registrando...',
    no_account: '¿No tienes cuenta?',
    have_account: '¿Ya tienes cuenta?',
    dashboard_title: 'Pipeline',
    menu_seguimiento: 'Seguimiento',
    menu_alta: 'Alta de Cuenta',
    menu_renovaciones: 'Renovaciones',
    logout: 'Salir',
    welcome: 'Bienvenido',
    error_registration: 'Error en el registro',
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    next: 'Siguiente',
    back: 'Anterior',
    finish: 'Terminar',
    actions: 'Acciones',
    detail: 'Detalle',
    new_opportunity: 'Nueva Oportunidad',
    new_case: 'Nuevo Caso',
    return_accounts: 'Volver a Cuentas',
    select: 'Seleccione...',
    won: 'Ganada',
    lost: 'Perdida',

    // Headers
    header_accounts: 'Bandeja de Cuentas',
    header_tracking: 'Bandeja de Seguimiento',
    header_renewals: 'Bandeja de Renovaciones',
    header_new_account: 'Alta de Cuentas',
    header_new_case: 'Alta de Caso',
    header_negotiation: 'Negociación',
    header_emission: 'Emisión',

    // Accounts / New Account
    account: 'Cuenta',
    identifier: 'Identificador',
    industry: 'Industria',
    ramo: 'Ramo',
    subramo: 'Subramo',
    business_type: 'Giro de Negocio',
    exp_type: 'Tipo de Experiencia',
    stage: 'Etapa',
    start_date: 'Inicio Vigencia',
    target_premium: 'Prima Objetivo',
    integral_care: 'Cuenta con Cuidado Integral',
    agent_code: 'Clave del Agente',
    agent_name: 'Nombre del Agente',
    promoter: 'Promotor',
    territory: 'Territorio',
    office: 'Oficina',
    channel: 'Canal',
    cost_center: 'Centro de Costos',
    new_channel: 'Nuevo para el conducto',
    nearshoring: 'Nearshoring',
    planmed: 'Cuenta con Planmed',
    plan: 'Plan',
    quoted_premium: 'Prima Cotizada',
    population_incisos: 'Población / Incisos / Ubicaciones',
    instance_folio: 'Instancia / Folio',
    underwriter: 'Responsable Suscripción',
    req_date: 'Fecha Solicitud',
    delivery_date: 'Fecha Entrega',
    observations: 'Observaciones',
    section_general: 'A. Información General de la Cuenta',
    section_agent: 'B. Datos del Agente',
    section_product: 'C. Configuración del Producto y Suscripción',
    section_observations: 'D. Observaciones',

    // Negotiation
    stayed: '¿Se quedó?',
    insured_pop: 'Población Asegurada',
    status: 'Estatus',
    insured_premium: 'Prima Asegurados',
    loss_data: 'Datos de Pérdida',
    loss_reason: 'Motivo de no ganado',
    winning_insurer: 'Aseguradora ganadora',
    comp_premium: 'Prima ofertada por la competencia',
    integral_care_section: 'Cuidado Integral',
    integral_pop: 'Población',
    integral_premium: 'Prima',
    capture_negotiation: 'Captura de Negociación',

    // Emission
    capture_emission: 'Captura de Emisión',
    folio_date: 'Fecha de ingreso de folio de emisión',
    emission_date: 'Fecha emisión',
    num_policies: 'Número de pólizas emitidas',
    policy: 'Póliza o polizario',
    emitted_pop: 'Población emitida (General)',
    integral_pop_emitted: 'Población Cuidado Integral',
    integral_premium_emitted: 'Prima Cuidado Integral',

    // Table Columns
    col_number: 'NÚMERO',
    col_account: 'CUENTA',
    col_line: 'RAMO',
    col_step: 'PASO',
    col_type: 'TIPO',
    col_subtype: 'SUBTIPO',
    col_status: 'ESTADO',
    col_actions: 'ACCIONES',

    // Messages
    no_accounts: 'No se encontraron cuentas',
    no_cases: 'No se encontraron pantallas existentes',
    select_account: 'Selecciona una cuenta para ver los casos',
    search_placeholder: 'Buscar por Razón Social o Identificador...',
    active_cases_for: 'Casos activos para:',
    page: 'Página',
    of: 'de',
    case_management: 'Gestión de Caso',
    account_data: 'Datos de la Cuenta',
    new_account_title: 'Alta de Nueva Cuenta',
    stage_alta_desc: 'Registro inicial de la cuenta y la oportunidad.',
    advance_negotiation: 'Avanzar a Negociación',
    negotiation: 'Negociación',
    save_advance: 'Guardar y Avanzar',
    emission: 'Emisión',
    finish_process: 'Terminar Proceso',
    success_save: 'Guardado correctamente',
    success_update: 'Actualizado correctamente',
    success_create: 'Creado correctamente'
  },
  en: {
    // General
    login: 'Log In',
    register: 'Sign Up',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    create_account: 'Create Account',
    entering: 'Logging in...',
    registering: 'Registering...',
    no_account: 'No account?',
    have_account: 'Already have an account?',
    dashboard_title: 'Pipeline',
    menu_seguimiento: 'Pipeline',
    menu_alta: 'New Account',
    menu_renovaciones: 'Renewals',
    logout: 'Log Out',
    welcome: 'Welcome',
    error_registration: 'Registration error',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    actions: 'Actions',
    detail: 'Detail',
    new_opportunity: 'New Opportunity',
    new_case: 'New Case',
    return_accounts: 'Back to Accounts',
    select: 'Select...',
    won: 'Won',
    lost: 'Lost',

    // Headers
    header_accounts: 'Accounts Tray',
    header_tracking: 'Tracking Tray',
    header_renewals: 'Renewals Tray',
    header_new_account: 'New Account',
    header_new_case: 'New Case',
    header_negotiation: 'Negotiation',
    header_emission: 'Emission',

    // Accounts / New Account
    account: 'Account',
    identifier: 'ID',
    industry: 'Industry',
    ramo: 'Line of Business',
    subramo: 'Sub-line',
    business_type: 'Business Type',
    exp_type: 'Experience Type',
    stage: 'Stage',
    start_date: 'Start Date',
    target_premium: 'Target Premium',
    integral_care: 'Has Integral Care',
    agent_code: 'Agent Code',
    agent_name: 'Agent Name',
    promoter: 'Promoter',
    territory: 'Territory',
    office: 'Office',
    channel: 'Channel',
    cost_center: 'Cost Center',
    new_channel: 'New for Channel',
    nearshoring: 'Nearshoring',
    planmed: 'Has Planmed',
    plan: 'Plan',
    quoted_premium: 'Quoted Premium',
    population_incisos: 'Population / Items / Locations',
    instance_folio: 'Instance / Folio',
    underwriter: 'Underwriter',
    req_date: 'Request Date',
    delivery_date: 'Delivery Date',
    observations: 'Observations',
    section_general: 'A. General Account Information',
    section_agent: 'B. Agent Data',
    section_product: 'C. Product & Subscription Config',
    section_observations: 'D. Observations',

    // Negotiation
    stayed: 'Retained?',
    insured_pop: 'Insured Population',
    status: 'Status',
    insured_premium: 'Insured Premium',
    loss_data: 'Loss Data',
    loss_reason: 'Loss Reason',
    winning_insurer: 'Winning Insurer',
    comp_premium: 'Competitor Premium',
    integral_care_section: 'Integral Care',
    integral_pop: 'Population',
    integral_premium: 'Premium',
    capture_negotiation: 'Negotiation Capture',

    // Emission
    capture_emission: 'Emission Capture',
    folio_date: 'Folio Entry Date',
    emission_date: 'Emission Date',
    num_policies: 'Number of Policies',
    policy: 'Policy Number',
    emitted_pop: 'Emitted Population (General)',
    integral_pop_emitted: 'Integral Care Population',
    integral_premium_emitted: 'Integral Care Premium',

    // Table Columns
    col_number: 'NUMBER',
    col_account: 'ACCOUNT',
    col_line: 'LOB',
    col_step: 'STEP',
    col_type: 'TYPE',
    col_subtype: 'SUBTYPE',
    col_status: 'STATUS',
    col_actions: 'ACTIONS',

    // Messages
    no_accounts: 'No accounts found',
    no_cases: 'No existing screens found',
    select_account: 'Select an account to view cases',
    search_placeholder: 'Search by Name or ID...',
    active_cases_for: 'Active cases for:',
    page: 'Page',
    of: 'of',
    case_management: 'Case Management',
    account_data: 'Account Data',
    new_account_title: 'New Account Registration',
    stage_alta_desc: 'Initial registration of account and opportunity.',
    advance_negotiation: 'Advance to Negotiation',
    negotiation: 'Negotiation',
    save_advance: 'Save and Advance',
    emission: 'Emission',
    finish_process: 'Finish Process',
    success_save: 'Saved successfully',
    success_update: 'Updated successfully',
    success_create: 'Created successfully'
  },
  pt: {
    // General
    login: 'Entrar',
    register: 'Registrar',
    email: 'Email',
    password: 'Senha',
    name: 'Nome',
    create_account: 'Criar Conta',
    entering: 'Entrando...',
    registering: 'Registrando...',
    no_account: 'Não tem conta?',
    have_account: 'Já tem conta?',
    dashboard_title: 'Pipeline',
    menu_seguimiento: 'Seguimento',
    menu_alta: 'Nova Conta',
    menu_renovaciones: 'Renovações',
    logout: 'Sair',
    welcome: 'Bem-vindo',
    error_registration: 'Erro no registro',
    loading: 'Carregando...',
    save: 'Salvar',
    cancel: 'Cancelar',
    next: 'Próximo',
    back: 'Voltar',
    finish: 'Terminar',
    actions: 'Ações',
    detail: 'Detalhe',
    new_opportunity: 'Nova Oportunidade',
    new_case: 'Novo Caso',
    return_accounts: 'Voltar para Contas',
    select: 'Selecione...',
    won: 'Ganha',
    lost: 'Perdida',

    // Headers
    header_accounts: 'Bandeja de Contas',
    header_tracking: 'Bandeja de Seguimento',
    header_renewals: 'Bandeja de Renovações',
    header_new_account: 'Nova Conta',
    header_new_case: 'Novo Caso',
    header_negotiation: 'Negociação',
    header_emission: 'Emissão',

    // Accounts / New Account
    account: 'Conta',
    identifier: 'Identificador',
    industry: 'Indústria',
    ramo: 'Ramo',
    subramo: 'Sub-ramo',
    business_type: 'Tipo de Negócio',
    exp_type: 'Tipo de Experiência',
    stage: 'Etapa',
    start_date: 'Início Vigência',
    target_premium: 'Prêmio Alvo',
    integral_care: 'Tem Cuidado Integral',
    agent_code: 'Cód. Agente',
    agent_name: 'Nome do Agente',
    promoter: 'Promotor',
    territory: 'Território',
    office: 'Escritório',
    channel: 'Canal',
    cost_center: 'Centro de Custo',
    new_channel: 'Novo para o canal',
    nearshoring: 'Nearshoring',
    planmed: 'Tem Planmed',
    plan: 'Plano',
    quoted_premium: 'Prêmio Cotado',
    population_incisos: 'População / Itens / Locais',
    instance_folio: 'Instância / Folio',
    underwriter: 'Subscritor',
    req_date: 'Data Solicitação',
    delivery_date: 'Data Entrega',
    observations: 'Observações',
    section_general: 'A. Informações Gerais da Conta',
    section_agent: 'B. Dados do Agente',
    section_product: 'C. Configuração do Produto',
    section_observations: 'D. Observações',

    // Negotiation
    stayed: 'Ficou?',
    insured_pop: 'População Segurada',
    status: 'Status',
    insured_premium: 'Prêmio Segurados',
    loss_data: 'Dados de Perda',
    loss_reason: 'Motivo da perda',
    winning_insurer: 'Seguradora vencedora',
    comp_premium: 'Prêmio da concorrência',
    integral_care_section: 'Cuidado Integral',
    integral_pop: 'População',
    integral_premium: 'Prêmio',
    capture_negotiation: 'Captura de Negociação',

    // Emission
    capture_emission: 'Captura de Emissão',
    folio_date: 'Data entrada folio',
    emission_date: 'Data emissão',
    num_policies: 'Número de apólices',
    policy: 'Apólice',
    emitted_pop: 'População emitida (Geral)',
    integral_pop_emitted: 'Pop. Cuidado Integral',
    integral_premium_emitted: 'Prêmio Cuidado Integral',

    // Table Columns
    col_number: 'NÚMERO',
    col_account: 'CONTA',
    col_line: 'RAMO',
    col_step: 'PASSO',
    col_type: 'TIPO',
    col_subtype: 'SUBTIPO',
    col_status: 'STATUS',
    col_actions: 'AÇÕES',

    // Messages
    no_accounts: 'Nenhuma conta encontrada',
    no_cases: 'Nenhum caso encontrado',
    select_account: 'Selecione uma conta para ver',
    search_placeholder: 'Buscar por Razão Social ou Identificador...',
    active_cases_for: 'Casos ativos para:',
    page: 'Página',
    of: 'de',
    case_management: 'Gestão de Caso',
    account_data: 'Dados da Conta',
    new_account_title: 'Registro de Nova Conta',
    stage_alta_desc: 'Registro inicial da conta e oportunidade.',
    advance_negotiation: 'Avançar para Negociação',
    negotiation: 'Negociação',
    save_advance: 'Salvar e Avançar',
    emission: 'Emissão',
    finish_process: 'Terminar Processo',
    success_save: 'Salvo com sucesso',
    success_update: 'Atualizado com sucesso',
    success_create: 'Criado com sucesso'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['es']) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: keyof typeof translations['es']) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
